Repository Deltares/D-FAST_Bank_Erosion, pull requests merged in 2025-04, with the labels that each got.

#44 Task/dfast 267 create unit tests docstring for configfile class
  poetry.lock
  pyproject.toml
  src/dfastbe/io.py
  tests/test_io.py
Labels: testing, refactor

#48 Refactor CLI
  src/dfastbe/__main__.py
  src/dfastbe/cmd.py
  src/dfastbe/io.py
  tests/context.py
  tests/data/erosion/output/banklines/bank_areas.dbf
  tests/data/erosion/output/banklines/bankfile.dbf
  tests/data/erosion/output/banklines/bankline_fragments_per_bank_area.dbf
  tests/data/erosion/output/banklines/raw_detected_bankline_fragments.dbf
  tests/test_cli_main.py
  tests/test_io.py
Labels: enhancement, refactor

#71 fix binaries tests
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  docs/mkdocs/guides/testing.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests-dist/test_basic.py
  tests-dist/test_batch.py
  tests/test_binaries/conftest.py
  tests/test_binaries/context.py
  tests/test_binaries/test_basic.py
  tests/test_binaries/test_batch.py
  tests/test_io.py
Labels: bug, testing, dev

#78 Task/dfast 281 group simulationobject methods in class
  src/dfastbe/bank_erosion.py
  src/dfastbe/bank_lines.py
  src/dfastbe/io.py
  src/dfastbe/support.py
  tests/test_io.py
Labels: refactor

#87 Move teamcity configurations to github repo
  .teamcity/DFastBETests/build_main.kt
  .teamcity/DFastBETests/build_terminal.kt
  .teamcity/DFastBETests/conda_template.kt
  .teamcity/DFastBETests/latex_manual.kt
  .teamcity/DFastBETests/pom.xml
  .teamcity/DFastBETests/settings.kts
  .teamcity/DFastBETests/signed_release.kt
  .teamcity/DFastBETests/signed_release_terminal.kt
  .teamcity/DFastBETests/test_binaries.kt
  .teamcity/DFastBETests/unit_tests.kt
  docs/mkdocs/guides/teamcity-ci.md
Labels: dev, ci

#93 Task/dfast 294 refactor erosion class
  src/dfastbe/__init__.py
  src/dfastbe/bank_erosion/__init__.py
  src/dfastbe/bank_erosion/bank_erosion.py
  src/dfastbe/bank_erosion/data_models.py
  src/dfastbe/bank_erosion/utils.py
  src/dfastbe/bank_lines/__init__.py
  src/dfastbe/bank_lines/bank_lines.py
  src/dfastbe/bank_lines/data_models.py
  src/dfastbe/cmd.py
  src/dfastbe/gui.py
  src/dfastbe/io.py
  src/dfastbe/kernel.py
  src/dfastbe/plotting.py
  src/dfastbe/support.py
  tests/data/files/Meuse.def
  tests/data/files/e02_f001_c011_simplechannel_map.nc
  tests/data/files/messages.UK.ini
  tests/data/files/read_waqua_xyz_test.xyc
  tests/test1/test1.ini
  tests/test_bank_lines/test_bank_lines.py
  tests/test_bank_lines/test_bank_lines_data_models.py
  tests/test_erosion/test_bank_erosion.py
  tests/test_erosion/test_data_models.py
  tests/test_io.py
  tests/test_structures.py
Labels: refactor
